spring:
  application:
    name: "newsfeed"
  datasource:
    url: "jdbc:h2:~/newsfeed/newsfeed"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
server:
  port: 8081

logging:
  level:
    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.springframework.security: DEBUG
#    reactor:
#      netty: DEBUG

jwt:
  secret:
    key: "036c4fe3ec667532545b9e8fa7e2a98a22f439dff102623c097715060e2da68c"
  expiry-millis: 300000 # 5?

cloud:
  aws:
    s3:
      bucket: "spartanewsfeed"
    stack.auto: false
    region.static: "ap-northeast-2"
    credentials:
      accessKey: "AKIAYS2NVGZSEWGRWCME"
      secretKey: "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"